name: Deploy Site

on:
    push:
        branches:
            - main # Activa el job cuando se hace un push a la rama main
    workflow_dispatch:

permissions: # sirve para dar permisos a los jobs
    contents: write # permite escribir en el repositorio

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4 # Clona el repositorio en el runner

            - name: Setup Node.js
              uses: actions/setup-node@v4 # Configura Node.js
              with:
                node-version: '20'
                cache: 'npm'
            
            - name: Install Dependencies # Instala las dependencias
              run: npm install

            - name: Build # Compila el proyecto
              run: npm run build

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                branch: gh-pages
                folder: dist
                token: ${{ secrets.GITHUB_TOKEN }}
                clean: true